nautobot_firewall_models/urls.py
"""Django urlpatterns declaration for nautobot_firewall_models plugin."""

from django.templatetags.static import static
from django.urls import path
from django.views.generic import RedirectView
from nautobot.core.views.routers import NautobotUIViewSetRouter
from nautobot.extras.views import ObjectChangeLogView, ObjectNotesView

from nautobot_firewall_models import models
from nautobot_firewall_models.views import (
    fqdn,
    iprange,
    zone,
    address_object,
    address_object_group,
    application_object,
    application_object_group,
    service_object,
    service_object_group,
    user_object,
    user_object_group,
    policy_rule,
    policy,
    nat_policy,
    capirca_policy,
)
from nautobot_firewall_models.views.nat_policy import NATPolicyUIViewSet
from nautobot_firewall_models.views.nat_policy_rule import NATPolicyRuleUIViewSet

router = NautobotUIViewSetRouter()
router.register("nat-policy", NATPolicyUIViewSet)
router.register("nat-policy-rule", NATPolicyRuleUIViewSet)

urlpatterns = [
    # FQDN URLs
    path("fqdn/", fqdn.FQDNListView.as_view(), name="fqdn_list"),
    # Order is important for these URLs to work (add/delete/edit) to be before any that require uuid/slug
    path("fqdn/add/", fqdn.FQDNEditView.as_view(), name="fqdn_add"),
    path("fqdn/delete/", fqdn.FQDNBulkDeleteView.as_view(), name="fqdn_bulk_delete"),
    path("fqdn/edit/", fqdn.FQDNBulkEditView.as_view(), name="fqdn_bulk_edit"),
    path("fqdn/<uuid:pk>/", fqdn.FQDNView.as_view(), name="fqdn"),
    path("fqdn/<uuid:pk>/delete/", fqdn.FQDNDeleteView.as_view(), name="fqdn_delete"),
    path("fqdn/<uuid:pk>/edit/", fqdn.FQDNEditView.as_view(), name="fqdn_edit"),
    path(
        "fqdn/<uuid:pk>/changelog/",
        ObjectChangeLogView.as_view(),
        name="fqdn_changelog",
        kwargs={"model": models.FQDN},
    ),
    path(
        "fqdn/<uuid:pk>/notes/",
        ObjectNotesView.as_view(),
        name="fqdn_notes",
        kwargs={"model": models.FQDN},
    ),
    # IPRange URLs
    path("ip-range/", iprange.IPRangeListView.as_view(), name="iprange_list"),
    # Order is important for these URLs to work (add/delete/edit) to be before any that require uuid/slug
    path("ip-range/add/", iprange.IPRangeEditView.as_view(), name="iprange_add"),
    path("ip-range/delete/", iprange.IPRangeBulkDeleteView.as_view(), name="iprange_bulk_delete"),
    path("ip-range/edit/", iprange.IPRangeBulkEditView.as_view(), name="iprange_bulk_edit"),
    path("ip-range/<uuid:pk>/", iprange.IPRangeView.as_view(), name="iprange"),
    path("ip-range/<uuid:pk>/delete/", iprange.IPRangeDeleteView.as_view(), name="iprange_delete"),
    path("ip-range/<uuid:pk>/edit/", iprange.IPRangeEditView.as_view(), name="iprange_edit"),
    path(
        "ip-range/<uuid:pk>/changelog/",
        ObjectChangeLogView.as_view(),
        name="iprange_changelog",
        kwargs={"model": models.IPRange},
    ),
    path(
        "ip-range/<uuid:pk>/notes/",
        ObjectNotesView.as_view(),
        name="iprange_notes",
        kwargs={"model": models.IPRange},
    ),
    # AddressObject URLs
    path("address-object/", address_object.AddressObjectListView.as_view(), name="addressobject_list"),
    # Order is important for these URLs to work (add/delete/edit) to be before any that require uuid/slug
    path("address-object/add/", address_object.AddressObjectEditView.as_view(), name="addressobject_add"),
    path(
        "address-object/delete/", address_object.AddressObjectBulkDeleteView.as_view(), name="addressobject_bulk_delete"
    ),
    path("address-object/edit/", address_object.AddressObjectBulkEditView.as_view(), name="addressobject_bulk_edit"),
    path("address-object/<uuid:pk>/", address_object.AddressObjectView.as_view(), name="addressobject"),
    path(
        "address-object/<uuid:pk>/delete/",
        address_object.AddressObjectDeleteView.as_view(),
        name="addressobject_delete",
    ),
    path("address-object/<uuid:pk>/edit/", address_object.AddressObjectEditView.as_view(), name="addressobject_edit"),
    path(
        "address-object/<uuid:pk>/changelog/",
        ObjectChangeLogView.as_view(),
        name="addressobject_changelog",
        kwargs={"model": models.AddressObject},
    ),
    path(
        "address-object/<uuid:pk>/notes/",
        ObjectNotesView.as_view(),
        name="addressobject_notes",
        kwargs={"model": models.AddressObject},
    ),
    # AddressObjectGroup URLs
    path(
        "address-object-group/",
        address_object_group.AddressObjectGroupListView.as_view(),
        name="addressobjectgroup_list",
    ),
    # Order is important for these URLs to work (add/delete/edit) to be before any that require uuid/slug
    path(
        "address-object-group/add/",
        address_object_group.AddressObjectGroupEditView.as_view(),
        name="addressobjectgroup_add",
    ),
    path(
        "address-object-group/delete/",
        address_object_group.AddressObjectGroupBulkDeleteView.as_view(),
        name="addressobjectgroup_bulk_delete",
    ),
    path(
        "address-object-group/edit/",
        address_object_group.AddressObjectGroupBulkEditView.as_view(),
        name="addressobjectgroup_bulk_edit",
    ),
    path(
        "address-object-group/<uuid:pk>/",
        address_object_group.AddressObjectGroupView.as_view(),
        name="addressobjectgroup",
    ),
    path(
        "address-object-group/<uuid:pk>/delete/",
        address_object_group.AddressObjectGroupDeleteView.as_view(),
        name="addressobjectgroup_delete",
    ),
    path(
        "address-object-group/<uuid:pk>/edit/",
        address_object_group.AddressObjectGroupEditView.as_view(),
        name="addressobjectgroup_edit",
    ),
    path(
        "address-group/<uuid:pk>/changelog/",
        ObjectChangeLogView.as_view(),
        name="addressobjectgroup_changelog",
        kwargs={"model": models.AddressObjectGroup},
    ),
    path(
        "address-group/<uuid:pk>/notes/",
        ObjectNotesView.as_view(),
        name="addressobjectgroup_notes",
        kwargs={"model": models.AddressObjectGroup},
    ),
    # ApplicationObject URLs
    path("application-object/", application_object.ApplicationObjectListView.as_view(), name="applicationobject_list"),
    # Order is important for these URLs to work (add/delete/edit) to be before any that require uuid/slug
    path(
        "application-object/add/", application_object.ApplicationObjectEditView.as_view(), name="applicationobject_add"
    ),
    path(
        "application-object/delete/",
        application_object.ApplicationObjectBulkDeleteView.as_view(),
        name="applicationobject_bulk_delete",
    ),
    path(
        "application-object/edit/",
        application_object.ApplicationObjectBulkEditView.as_view(),
        name="applicationobject_bulk_edit",
    ),
    path("application-object/<uuid:pk>/", application_object.ApplicationObjectView.as_view(), name="applicationobject"),
    path(
        "application-object/<uuid:pk>/delete/",
        application_object.ApplicationObjectDeleteView.as_view(),
        name="applicationobject_delete",
    ),
    path(
        "application-object/<uuid:pk>/edit/",
        application_object.ApplicationObjectEditView.as_view(),
        name="applicationobject_edit",
    ),
    path(
        "application-object/<uuid:pk>/changelog/",
        ObjectChangeLogView.as_view(),
        name="applicationobject_changelog",
        kwargs={"model": models.ApplicationObject},
    ),
    path(
        "application-object/<uuid:pk>/notes/",
        ObjectNotesView.as_view(),
        name="applicationobject_notes",
        kwargs={"model": models.ApplicationObject},
    ),
    # ApplicationObjectGroup URLs
    path(
        "application-object-group/",
        application_object_group.ApplicationObjectGroupListView.as_view(),
        name="applicationobjectgroup_list",
    ),
    # Order is important for these URLs to work (add/delete/edit) to be before any that require uuid/slug
    path(
        "application-object-group/add/",
        application_object_group.ApplicationObjectGroupEditView.as_view(),
        name="applicationobjectgroup_add",
    ),
    path(
        "application-object-group/delete/",
        application_object_group.ApplicationObjectGroupBulkDeleteView.as_view(),
        name="applicationobjectgroup_bulk_delete",
    ),
    path(
        "application-object-group/edit/",
        application_object_group.ApplicationObjectGroupBulkEditView.as_view(),
        name="applicationobjectgroup_bulk_edit",
    ),
    path(
        "application-object-group/<uuid:pk>/",
        application_object_group.ApplicationObjectGroupView.as_view(),
        name="applicationobjectgroup",
    ),
    path(
        "application-object-group/<uuid:pk>/delete/",
        application_object_group.ApplicationObjectGroupDeleteView.as_view(),
        name="applicationobjectgroup_delete",
    ),
    path(
        "application-object-group/<uuid:pk>/edit/",
        application_object_group.ApplicationObjectGroupEditView.as_view(),
        name="applicationobjectgroup_edit",
    ),
    path(
        "application-group/<uuid:pk>/changelog/",
        ObjectChangeLogView.as_view(),
        name="applicationobjectgroup_changelog",
        kwargs={"model": models.ApplicationObjectGroup},
    ),
    path(
        "application-group/<uuid:pk>/notes/",
        ObjectNotesView.as_view(),
        name="applicationobjectgroup_notes",
        kwargs={"model": models.ApplicationObjectGroup},
    ),
    # ServiceObject URLs
    path("service-object/", service_object.ServiceObjectListView.as_view(), name="serviceobject_list"),
    # Order is important for these URLs to work (add/delete/edit) to be before any that require uuid/slug
    path("service-object/add/", service_object.ServiceObjectEditView.as_view(), name="serviceobject_add"),
    path(

nautobot_firewall_models/models/capirca_policy.py
"""Models for the Capirca Configurations."""
# pylint: disable=duplicate-code
import logging

from django.db import models
from django.urls import reverse
from django.utils.module_loading import import_string
from nautobot.core.models.generics import PrimaryModel
from nautobot.extras.utils import extras_features

from nautobot_firewall_models.constants import PLUGIN_CFG
from nautobot_firewall_models.utils.capirca import DevicePolicyToCapirca

LOGGER = logging.getLogger(__name__)


@extras_features(
    "custom_fields",
    "custom_links",
    "custom_validators",
    "export_templates",
    "graphql",
    "relationships",
    "statuses",
    "webhooks",
)
class CapircaPolicy(PrimaryModel):
    """CapircaPolicy model."""

    device = models.OneToOneField(to="dcim.Device", blank=True, null=True, on_delete=models.CASCADE)
    pol = models.TextField(blank=True, null=True)
    net = models.TextField(blank=True, null=True)
    svc = models.TextField(blank=True, null=True)
    cfg = models.TextField(blank=True, null=True)

    csv_headers = ["device"]

    class Meta:
        """Meta class."""

        ordering = ["device"]
        verbose_name_plural = "Capirca Policies"

    def get_absolute_url(self):
        """Return detail view URL."""
        return reverse("plugins:nautobot_firewall_models:capircapolicy", args=[self.pk])

    def __str__(self):
        """Stringify instance."""
        return f"Capirca Policy -> {self.device.name}"

    def save(self, *args, **kwargs):
        """Update the firewall rules as updates are made."""
        if not PLUGIN_CFG.get("custom_capirca"):
            LOGGER.debug("Running standard Capirca conversion")
            cap_obj = DevicePolicyToCapirca(self.device)
            cap_obj.get_all_capirca_cfg()
            self.pol = cap_obj.pol_file
            self.svc = cap_obj.svc_file
            self.net = cap_obj.net_file
            self.cfg = cap_obj.cfg_file
        else:
            LOGGER.debug("Running custom conversion from function: `%s`", str(PLUGIN_CFG["custom_capirca"]))
            self.pol, self.svc, self.net, self.cfg = import_string(PLUGIN_CFG["custom_capirca"])(self.device)

        super().save(*args, **kwargs)

nautobot_firewall_models/models/zone.py
"""Models for the Firewall plugin."""
# pylint: disable=duplicate-code

from django.db import models
from django.urls import reverse
from nautobot.core.models.generics import BaseModel, PrimaryModel
from nautobot.extras.models import StatusField
from nautobot.extras.utils import extras_features

from nautobot_firewall_models.utils import get_default_status


###########################
# Core Models
###########################


@extras_features(
    "custom_fields",
    "custom_links",
    "custom_validators",
    "export_templates",
    "graphql",
    "relationships",
    "statuses",
    "webhooks",
)
class Zone(PrimaryModel):
    """Zones common on firewalls and are typically seen as representations of area (e.g. DMZ trust untrust)."""

    description = models.CharField(
        max_length=200,
        blank=True,
    )
    name = models.CharField(max_length=100, unique=True, help_text="Name of the zone (e.g. trust)")
    vrfs = models.ManyToManyField(to="ipam.VRF", blank=True, through="ZoneVRFM2M", related_name="zones")
    interfaces = models.ManyToManyField(
        to="dcim.Interface", blank=True, through="ZoneInterfaceM2M", related_name="zones"
    )
    status = StatusField(
        on_delete=models.PROTECT,
        related_name="%(app_label)s_%(class)s_related",  # e.g. dcim_device_related
        default=get_default_status,
    )

    class Meta:
        """Meta class."""

        ordering = ["name"]
        verbose_name_plural = "Zones"

    def get_absolute_url(self):
        """Return detail view URL."""
        return reverse("plugins:nautobot_firewall_models:zone", args=[self.pk])

    def __str__(self):
        """Stringify instance."""
        return self.name


###########################
# Through Models
###########################


class ZoneInterfaceM2M(BaseModel):
    """Custom through model to on_delete=models.PROTECT to prevent deleting associated Interface if assigned to a Zone."""

    zone = models.ForeignKey("nautobot_firewall_models.Zone", on_delete=models.CASCADE)
    interface = models.ForeignKey("dcim.Interface", on_delete=models.PROTECT)


class ZoneVRFM2M(BaseModel):
    """Custom through model to on_delete=models.PROTECT to prevent deleting associated VRF if assigned to a Zone."""

    zone = models.ForeignKey("nautobot_firewall_models.Zone", on_delete=models.CASCADE)
    vrf = models.ForeignKey("ipam.vrf", on_delete=models.PROTECT)

nautobot_firewall_models/views/address_object.py
"""Address Object Views."""

from nautobot.core.views import generic

from nautobot_firewall_models import filters, forms, models, tables


class AddressObjectListView(generic.ObjectListView):
    """List view."""

    queryset = models.AddressObject.objects.all()
    filterset = filters.AddressObjectFilterSet
    filterset_form = forms.AddressObjectFilterForm
    table = tables.AddressObjectTable
    action_buttons = ("add",)


class AddressObjectView(generic.ObjectView):
    """Detail view."""

    queryset = models.AddressObject.objects.all()


class AddressObjectDeleteView(generic.ObjectDeleteView):
    """Delete view."""

    queryset = models.AddressObject.objects.all()


class AddressObjectEditView(generic.ObjectEditView):
    """Edit view."""

    queryset = models.AddressObject.objects.all()
    model_form = forms.AddressObjectForm


class AddressObjectBulkDeleteView(generic.BulkDeleteView):
    """View for deleting one or more AddressObject records."""

    queryset = models.AddressObject.objects.all()
    table = tables.AddressObjectTable


class AddressObjectBulkEditView(generic.BulkEditView):
    """View for editing one or more AddressObject records."""

    queryset = models.AddressObject.objects.all()
    filterset = filters.AddressObjectFilterSet
    table = tables.AddressObjectTable
    form = forms.AddressObjectBulkEditForm

nautobot_firewall_models/views/address_object_group.py
"""Address Object Group Views."""

from nautobot.core.views import generic

from nautobot_firewall_models import filters, forms, models, tables


class AddressObjectGroupListView(generic.ObjectListView):
    """List view."""

    queryset = models.AddressObjectGroup.objects.all()
    filterset = filters.AddressObjectGroupFilterSet
    filterset_form = forms.AddressObjectGroupFilterForm
    table = tables.AddressObjectGroupTable
    action_buttons = ("add",)


class AddressObjectGroupView(generic.ObjectView):
    """Detail view."""

    queryset = models.AddressObjectGroup.objects.all()


class AddressObjectGroupDeleteView(generic.ObjectDeleteView):
    """Delete view."""

    queryset = models.AddressObjectGroup.objects.all()


class AddressObjectGroupEditView(generic.ObjectEditView):
    """Edit view."""

    queryset = models.AddressObjectGroup.objects.all()
    model_form = forms.AddressObjectGroupForm


class AddressObjectGroupBulkDeleteView(generic.BulkDeleteView):
    """View for deleting one or more AddressObjectGroup records."""

    queryset = models.AddressObjectGroup.objects.all()
    table = tables.AddressObjectGroupTable


class AddressObjectGroupBulkEditView(generic.BulkEditView):
    """View for editing one or more AddressObjectGroup records."""

    queryset = models.AddressObjectGroup.objects.all()
    filterset = filters.AddressObjectGroupFilterSet
    table = tables.AddressObjectGroupTable
    form = forms.AddressObjectGroupBulkEditForm

nautobot_firewall_models/templates/nautobot_firewall_models/addressobject.html
{% extends 'generic/object_detail.html' %}
{% load helpers %}

{% block content_left_page %}
    <div class="panel panel-default">
        <div class="panel-heading">
            <strong>Address Object</strong>
        </div>
        <table class="table table-hover panel-body attr-table">
            <tr>
                <td>Description</td>
                <td>{{ object.description|placeholder }}</td>
            </tr>
            <tr>
                <td>FQDN</td>
                <td>
                    {% if object.fqdn %}
                        <a href="{{ object.fqdn.get_absolute_url }}">{{ object.fqdn }}</a>
                    {% else %}
                        <span class="text-muted">None</span>
                    {% endif %}
                </td>
            </tr>
            <tr>
                <td>IP Range</td>
                <td>
                    {% if object.ip_range %}
                        <a href="{{ object.ip_range.get_absolute_url }}">{{ object.ip_range }}</a>
                    {% else %}
                        <span class="text-muted">None</span>
                    {% endif %}
                </td>
            </tr>
            <tr>
                <td>IP Address</td>
                <td>
                    {% if object.ip_address %}
                        <a href="{{ object.ip_address.get_absolute_url }}">{{ object.ip_address }}</a>
                    {% else %}
                        <span class="text-muted">None</span>
                    {% endif %}
                </td>
            </tr>
            <tr>
                <td>Prefix</td>
                <td>
                    {% if object.prefix %}
                        <a href="{{ object.prefix.get_absolute_url }}">{{ object.prefix }}</a>
                    {% else %}
                        <span class="text-muted">None</span>
                    {% endif %}
                </td>
            </tr>
            <tr>
                <td>Status</td>
                <td><span class="label" style="color: {{ object.status.color|fgcolor }}; background-color: #{{ object.status.color }}">{{ object.get_status_display }}</span></td>
            </tr>
        </table>
    </div>
{% endblock %}

nautobot_firewall_models/templates/nautobot_firewall_models/addressobjectgroup.html
{% extends 'generic/object_detail.html' %}
{% load helpers %}

{% block content_left_page %}
    <div class="panel panel-default">
        <div class="panel-heading">
            <strong>Address Object Group</strong>
        </div>
        <table class="table table-hover panel-body attr-table">
            <tr>
                <td>Description</td>
                <td>{{ object.description|placeholder }}</td>
            </tr>
            <tr>
                <td>Address Objects</td>
                <td>
                    <ul>
                        {% for i in object.address_objects.all %}
                            <li><a href="{{ i.get_absolute_url }}">{{ i|placeholder }}</a></li>
                        {% empty %}
                            None
                        {% endfor %}
                    </ul>
                </td>
            </tr>
            <tr>
                <td>Status</td>
                <td><span class="label" style="color: {{ object.status.color|fgcolor }}; background-color: #{{ object.status.color }}">{{ object.get_status_display }}</span></td>
            </tr>
        </table>
    </div>
{% endblock %}

nautobot_firewall_models/templates/nautobot_firewall_models/applicationobject.html
{% extends 'generic/object_detail.html' %}
{% load helpers %}

{% block content_left_page %}
<div class="panel panel-default">
  <div class="panel-heading">
    <strong>Application Object</strong>
  </div>
  <table class="table table-hover panel-body attr-table">
    <tr>
      <td>Name</td>
      <td>{{ object.name|placeholder }}</td>
    </tr>
    <tr>
      <td>Description</td>
      <td>{{ object.description|placeholder }}</td>
    </tr>
    <tr>
      <td>Category</td>
      <td>{{ object.category|placeholder }}</td>
    </tr>
    <tr>
      <td>Sub-Category</td>
      <td>{{ object.subcategory|placeholder }}</td>
    </tr>
    <tr>
      <td>Technology</td>
      <td>{{ object.technology|placeholder }}</td>
    </tr>
    <tr>
      <td>Risk</td>
      <td>{{ object.risk|placeholder }}</td>
    </tr>
    <tr>
      <td>Default Type</td>
      <td>{{ object.default_type|placeholder }}</td>
    </tr>
    <tr>
      <td>Default IP Protocol</td>
      <td>{{ object.default_ip_protocol|placeholder }}</td>
    </tr>
    <tr>
      <td>Status</td>
      <td>
        <span
          class="label"
          style="color: {{ object.status.color|fgcolor }}; background-color: #{{ object.status.color }}"
          >{{ object.get_status_display }}</span
        >
      </td>
    </tr>
  </table>
</div>
{% endblock %}

nautobot_firewall_models/templates/nautobot_firewall_models/capircapolicy.html
{% extends 'generic/object_detail.html' %}
{% load helpers %}
{% load buttons %}
{% load plugins %}
{% load fw_tags %}

{% block buttons %}
        {% plugin_buttons object %}
        {% if perms.nautobot_firewall_models.delete_capircapolicy %}
            {% delete_button object %}
        {% endif %}
{% endblock buttons %}

{% block content_left_page %}
<div class="panel panel-default">
    <div class="panel-heading">
        <strong>Capirca Object <a href="{% url 'plugins:nautobot_firewall_models:capircapolicy_devicedetail' pk=object.device.pk %}"><i class="mdi mdi-file-document-outline"></i></a></strong>
    </div>
    <table class="table table-hover panel-body attr-table">
        <tr>
            <td>Configuration</td>
            <td><pre>{{ object.cfg|render_truncate|placeholder }}</pre></td>
        </tr>
        <tr>
            <td>Policy File</td>
            <td><pre>{{ object.pol|render_truncate|placeholder }}</pre></td>
        </tr>
        <tr>
            <td>Services File</td>
            <td><pre>{{ object.svc|render_truncate|placeholder }}</pre></td>
        </tr>
        <tr>
            <td>Network File</td>
            <td><pre>{{ object.net|render_truncate|placeholder }}</pre></td>
        </tr>
    </table>
</div>

{% endblock %}

nautobot_firewall_models/templates/nautobot_firewall_models/iprange.html
{% extends 'generic/object_detail.html' %}
{% load helpers %}

{% block content_left_page %}
    <div class="panel panel-default">
        <div class="panel-heading">
            <strong>IP Range</strong>
        </div>
        <table class="table table-hover panel-body attr-table">
            <tr>
                <td>Description</td>
                <td>{{ object.description|placeholder }}</td>
            </tr>
            <tr>
                <td>Start Address</td>
                <td>{{ object.start_address }}</td>
            </tr>
            <tr>
                <td>End Address</td>
                <td>{{ object.end_address }}</td>
            </tr>
            <tr>
                <td>Size</td>
                <td>{{ object.size }}</td>
            </tr>
            <tr>
                <td>VRF</td>
                <td><a href="{{ object.vrf.get_absolute_url }}">{{ object.vrf|placeholder }}</a></td>
            </tr>
            <tr>
                <td>Status</td>
                <td><span class="label" style="color: {{ object.status.color|fgcolor }}; background-color: #{{ object.status.color }}">{{ object.get_status_display }}</span></td>
            </tr>
        </table>
    </div>
{% endblock %}

nautobot_firewall_models/templates/nautobot_firewall_models/natpolicy.html
{% extends 'nautobot_firewall_models/natpolicy_retrieve.html' %}
{% comment %}
    TODO: Remove this template, which only exists for compatibility with Notes and Changelog.
    See https://github.com/nautobot/nautobot/issues/2509, fixed in Nautobot v1.4.5
{% endcomment %}

nautobot_firewall_models/templates/nautobot_firewall_models/natpolicyrule.html
{% extends 'nautobot_firewall_models/natpolicyrule_retrieve.html' %}
{% comment %}
    TODO: Remove this template, which only exists for compatibility with Notes and Changelog.
    See https://github.com/nautobot/nautobot/issues/2509, fixed in Nautobot v1.4.5
{% endcomment %}

nautobot_firewall_models/templates/nautobot_firewall_models/serviceobject_edit.html
{% extends 'generic/object_edit.html' %}
{% load form_helpers %}
{% load helpers %}

{% block javascript %}
  {% if not editing %}
    <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title" id="exampleModalLabel">Duplicate Service Objects</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
          <div class="modal-body">The following Service Object(s) were found with the same IP Protocol and Port. Please confirm you would like to create a duplicated object.</div>
          <div class="modal-body">
            <ul id="duplicate_results"></ul>
          </div>
          <form enctype="multipart/form-data" method="post">
            {% csrf_token %}
            <input type="hidden" name="name" id="confirm_name">
            <input type="hidden" name="description" id="confirm_description">
            <input type="hidden" name="port" id="confirm_port">
            <input type="hidden" name="ip_protocol" id="confirm_ip_protocol">
            <input type="hidden" name="status" id="confirm_status">
            <select name="tags" id="confirm_tags" multiple hidden></select>
            <div class="modal-footer">
              <button type="submit" name="_create" class="btn btn-primary">Create</button>
              <button type="submit" name="_addanother" class="btn btn-primary">Create and Add Another</button>
              <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
            </div>
          </form>
        </div>
      </div>
    </div>
    <script>
      $(".form-horizontal").submit(function(event) {
        event.preventDefault();
        $("button[name='_create']").prop("disabled", true);
        $("button[name='_addanother']").prop("disabled", true);
        var base_url = "{% url 'plugins:nautobot_firewall_models:serviceobject_list' %}";
        var name = $("#id_name").val();
        var description = $("#id_description").val();
        var port = $("#id_port").val();
        var ip_protocol = $("#id_ip_protocol").val();
        var status = $("#id_status").val();
        var tags = $("#id_tags").children().clone();
        $.get(
          "{% url 'plugins-api:nautobot_firewall_models-api:serviceobject-list' %}", 
          {port: port, ip_protocol: ip_protocol}
        ).done(function(data){
          if (data.count > 0) {
            for (let i = 0; i < data.results.length; i++) {
              $("#duplicate_results").append(
                $("<li>").append(
                  $("<a>").attr("href", base_url+data.results[i].id+"/").html(data.results[i].name+": "+data.results[i].ip_protocol+" "+data.results[i].port)
                )
              )
            }
            $("#confirm_name").val(name);
            $("#confirm_description").val(description);
            $("#confirm_port").val(port);
            $("#confirm_ip_protocol").val(ip_protocol);
            $("#confirm_status").val(status);
            $("#confirm_tags").html(tags);
            $("button[name='_create']").prop("disabled", false);
            $("button[name='_addanother']").prop("disabled", false);
            $("#exampleModal").modal();
          } else {
            event.currentTarget.submit();
          }
        });
      });
    </script>
    {% endif %}
{% endblock %}